<script>
  import TodoItem from './TodoItem.svelte';
  import {
    getFirestore,
    collection,
    query,
    where,
    orderBy,
    doc,
    setDoc,
    deleteDoc,
    updateDoc,
    addDoc,
    Timestamp,
  } from 'firebase/firestore';
  import { collectionData } from 'rxfire/firestore';
  import { startWith } from 'rxjs/operators';

  // we get the instance of our db
  const db = getFirestore();

  // User ID passed from parent
  export let uid;

  // Default Form Text
  let text = 'some task';

  // create a reference of the collection
  const todosRef = collection(db, 'todos');

  // Query requires an index, see screenshot below
  // Create a query against the collection.
  const q = query(todosRef, where('uid', '==', uid), orderBy('created'));

  // this todos is an obervable - other approach would be to use the snapshot listner
  const todos = collectionData(q, 'id').pipe(startWith([]));

  async function add() {
    // this is taking the collection reference where we add a new document in our todos collection with a autogen id which we will add to the doc as well
    const dRef = await addDoc(todosRef, {
      uid,
      text,
      complete: false,
      created: Timestamp.now(),
    });

    // add the new autogenerated id in the doc - this will allow us to later perform uodate and deletion nicely
    await setDoc(
      doc(db, 'todos', dRef.id),
      {
        id: dRef.id,
      },
      { merge: true }
    );

    // empty the textbox once we are done
    text = '';
  }

  async function updateStatus(event) {
    const { id, newStatus } = event.detail;

    // the doc takes the id as reference which should be unique if you only want one of the document to be updated
    await updateDoc(doc(db, 'todos', id), { complete: newStatus });
  }

  async function removeItem(event) {
    const { id } = event.detail;
    await deleteDoc(doc(db, 'todos', id));
  }
</script>

<h1>Todo List</h1>
<table>
  {#each $todos as todo}
    <TodoItem {...todo} on:remove={removeItem} on:toggle={updateStatus} />
  {/each}
</table>

<h1>Add New</h1>
<input bind:value={text} />
<button on:click={add}>Add Task</button>

<style>
  input {
    display: block;
  }

  h1 {
    margin: 56px 0 32px;
    font-weight: 300;
    font-size: 28px;
    line-height: 24px;
    color: #333333;
    font-family: Proxima Nova, sans-serif;
  }

  table {
    border: 1px solid purple;
  }
</style>
